from components.messages.base.MessageBase import MessageBase


class AssistantMessage(MessageBase):
    """
    Assistant message representing a response from the AI assistant.

    This message is typically generated by the AI and sent to the user.
    """

    role: str = "assistant"
